#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml", "pydantic-settings"]
# ///
"""Generate README.md from the metadata.yml files (single source of truth).

The README index is a build artifact, not a hand-maintained file: every link is
derived from a folder's metadata title and its PDF on disk. This makes the
"forgot to add the new paper to the README" class of drift structurally
impossible (it was the cause of the 26-vs-23 Publications gap).

Usage:
  generate_readme.py            # rewrite README.md
  generate_readme.py --check    # exit 1 (with a diff) if README.md is stale
"""

import difflib
import sys

import publib

REPO_ROOT = publib.REPO_ROOT
README = REPO_ROOT / "README.md"

BANNER = "<!-- Generated by scripts/generate_readme.py from metadata.yml. Do not edit by hand; run `just readme`. -->"
INTRO = "This repository is a complete list of all publications and abstracts that I have published."


def link(title: str, dest: str) -> str:
    return f"- [{title}](<{dest}>)"


def entry_line(entry: publib.Entry) -> str:
    title = entry.metadata.get("title") or entry.title_slug
    dest = entry.rel_pdf or (entry.rel_folder + "/")
    return link(title, dest)


def unpublished_lines() -> list[str]:
    base = REPO_ROOT / "Unpublished"
    if not base.exists():
        return []
    lines = []
    for pdf in sorted(base.glob("*.pdf")):
        stem = pdf.stem
        head, _, tail = stem.partition(" ")
        title = tail if head.isdigit() and tail else stem
        lines.append(link(title, pdf.relative_to(REPO_ROOT).as_posix()))
    return lines


def render() -> str:
    entries = list(publib.iter_entries())
    pubs = [e for e in entries if e.kind == "Publication"]
    abstracts = [e for e in entries if e.kind == "Abstract"]

    parts: list[str] = [BANNER, "", "# Publications", "", INTRO, "", "## Publications", ""]
    parts += [entry_line(e) for e in pubs]
    parts += ["", "## Abstracts, Posters, and Presentations", ""]
    parts += [entry_line(e) for e in abstracts]

    unpub = unpublished_lines()
    if unpub:
        parts += ["", "## Non-Published Abstracts, Posters, etc.", ""]
        parts += unpub

    parts += ["", "<!-- ## Currently in Submission -->", ""]
    return "\n".join(parts)


def main() -> None:
    log = publib.get_logger("generate_readme")
    check = "--check" in sys.argv[1:]
    new = render()
    current = README.read_text() if README.exists() else ""

    if check:
        if new == current:
            log.info("complete", drift=False, elapsed_s=log.elapsed())
            log.flush()
            sys.exit(0)
        diff = "\n".join(
            difflib.unified_diff(
                current.splitlines(), new.splitlines(),
                fromfile="README.md (on disk)", tofile="README.md (generated)", lineterm="",
            )
        )
        print(diff, file=sys.stderr)
        log.error("stale_readme", hint="run `just readme`", elapsed_s=log.elapsed())
        log.flush()
        sys.exit(1)

    README.write_text(new)
    changed = new != current
    log.info("complete", changed=changed, elapsed_s=log.elapsed())
    log.flush()


if __name__ == "__main__":
    main()
